### ISSUE TITLE
baisse hashrate sur premier GPU 

### ISSUE THREAD

**Issue by ghost** [Akisoft41/qubic-hive#1]
Bonjour, saurais-tu pourquoi le premier GPU sort moins que les autres ? 

merci 

![1](https://github.com/Akisoft41/qubic-hive/assets/118174931/6b54d1f2-94fd-41d4-9ca7-e9c8886298eb)
![2](https://github.com/Akisoft41/qubic-hive/assets/118174931/3566c4d4-a193-45b7-bab2-b7ac011ed12e)
![3](https://github.com/Akisoft41/qubic-hive/assets/118174931/2821e3af-5cce-4147-b2b6-2758324c140c)

**Comment by Akisoft41** [comment]
Bonjour, c'est un bug connu du mineur Qubic.
Malheureusement, on ne peut rien faire, si ce n'est d'attendre une correction de la Team...

**Comment by ghost** [comment]
Ça marche merci
